version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://better_auth:password@postgres:5432/better_auth

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: better_auth
      POSTGRES_USER: better_auth
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: container_pgadmin
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data: